# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
_extends: .github:.github/settings.yml

# repo-specific settings

repository:
  name: "portefaix-inspec-gcp"
  description: "Inspec profile for Portefaix on Google Cloud Platform"
  topics: portefaix, inspec, gcp

labels:

## CLOUD PROVIDERS

- name: "cloud/gcp"
  description: "Cloud Provider / GCP"
  color: "068082"

## AREA

- name: "area/inspec"
  description: "Inspec"
  color: "cc317c"

- name: "area/github"
  description: "Github"
  color: "cc317c"

## DEPENDENCY

- name: "dependency/github"
  description: "Dependency Github Actions"
  color: "6fcb70"

- name: "dependency/inspec"
  description: "Dependency Inspec"
  color: "6fcb70"

## NEEDS

- name: "needs/triage"
  description: "Indicates an issue or PR lacks a `triage/foo` label and requires one."
  color: "D669BE"

- name: "needs/priority"
  description: "Indicates a PR lacks a `priority/foo` label and requires one."
  color: "D669BE"

- name: "needs/kind"
  description: "Indicates a PR lacks a `kind/foo` label and requires one."
  color: "D669BE"

- name: "needs/lifecycle"
  description: "Indicates a PR lacks a `lifecycle/foo` label and requires one."
  color: "D669BE"

- name: "needs/area"
  description: "Indicates an issue or PR lacks a `area/foo` label and requires one."
  color: "D669BE"

- name: "needs/size"
  description: "Indicates an issue or PR lacks a `size/foo` label and requires one."
  color: "D669BE"

- name: "needs/status"
  description: "Indicates an issue or PR lacks a `status/foo` label and requires one."
  color: "D669BE"

- name: "needs/cloud"
  description: "Indicates a PR lacks a `cloud/foo` label and requires one."
  color: "D669BE"

## SIZE

- name: "size/xs"
  description: "Size XS"
  color: "ededed"

- name: "size/s"
  description: "Size S"
  color: "ededed"

- name: "size/m"
  description: "Size M"
  color: "ededed"

- name: "size/l"
  description: "Size L"
  color: "ededed"

- name: "size/xl"
  description: "Size XL"
  color: "ededed"

## LIFECYCLE

- name: "lifecycle/waiting"
  description: "Indicates that an issue or PR is waiting a contributor."
  color: "75CA20"

- name: "lifecycle/active"
  description: "Indicates that an issue or PR is actively being worked on by a contributor."
  color: "75CA20"

- name: "lifecycle/frozen"
  description: "Indicates that an issue or PR should not be auto-closed due to staleness."
  color: "10D3EE"

- name: "lifecycle/stale"
  description: "Denotes an issue or PR has remained open with no activity and has become stale."
  color: "616F6C"

- name: "lifecycle/rotten"
  description: "Denotes an issue or PR that has aged beyond stale and will be auto-closed."
  color: "212F3D"

## STATUS

- name: "status/abandoned"
  description: "This issue or PR is no longer important"
  color: "000000"

- name: "status/available"
  description: "No one has claimed responsibility for resolving this issue"
  color: "c2e0c6"

- name: "status/blocked"
  description: "There is another issue or PR that needs to be resolved first"
  color: "ee0701"

- name: "status/in_progress"
  description: "This issue or PR is being worked on, and has someone assigned"
  color: "cccccc"

- name: "status/on_hold"
  description: "Similar to blocked, but is assigned to someone"
  color: "e99695"

- name: "status/proposal"
  description: "A new propoal"
  color: "d4c5f9"

- name: "status/review_needed"
  description: "The issue or PR needs to be reviewed"
  color: "fbca04"

## PRIORITY

- name: "priority/critical"
  description: "Highest priority. This should be dealt with ASAP"
  color: "ee0701"

- name: "priority/high"
  description: "After critical issues are fixed, these should be dealt with before any further issues"
  color: "d93f0b"

- name: "priority/medium"
  description: "This issue or PR may be useful, and needs some attention"
  color: "fbca04"

- name: "priority/low"
  description: "This issue can probably be picked up by anyone looking to contribute to the project, as an entry fix"
  color: "0e8a16"

- name: "priority/backlog"
  description: "Possibly useful, but not yet enough support to actually get it done"
  color: "fbca04"
